owner: mirzahilmi
repo: upptime

sites:
  - name: ICN Laboratory Website
    url: https://icn-filkom.ub.ac.id
  - name: BCC Website
    url: https://bcc.filkom.ub.ac.id

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** Monitor, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
